language: android
dist: xenial
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - android-19
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - chmod +x ./gradlew

script:
    - ./gradlew clean testDebug lintDebug --info